// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXruPlEBB3epBoqCTXlxJ_Ak2EOohSWOk',
    appId: '1:563746985689:web:d64bb771e764d2832010c8',
    messagingSenderId: '563746985689',
    projectId: 'thelostcity-45cef',
    authDomain: 'thelostcity-45cef.firebaseapp.com',
    storageBucket: 'thelostcity-45cef.firebasestorage.app',
    measurementId: 'G-7ZKBLNT8Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrIp1P9-f_c3ROQ-pv-02QCIsLS3g7vkE',
    appId: '1:563746985689:android:79c8d189c94e496c2010c8',
    messagingSenderId: '563746985689',
    projectId: 'thelostcity-45cef',
    storageBucket: 'thelostcity-45cef.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXruPlEBB3epBoqCTXlxJ_Ak2EOohSWOk',
    appId: '1:563746985689:web:9c5339e88b3972012010c8',
    messagingSenderId: '563746985689',
    projectId: 'thelostcity-45cef',
    authDomain: 'thelostcity-45cef.firebaseapp.com',
    storageBucket: 'thelostcity-45cef.firebasestorage.app',
    measurementId: 'G-1F6R89983D',
  );
}
